FROM docker.io/yobasystems/alpine-mariadb
#FROM yobasystems/alpine-mariadb
#RUN echo "CREATE DATABASE $DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;GRANT ALL PRIVILEGES ON $DATABASE.* TO $USER@localhost IDENTIFIED BY '$PASSWORD';FLUSH PRIVILEGES;" > /docker-entrypoint-initdb.d/initdb.sql
#COPY initdb.sql /docker-entrypoint-initdb.d/initdb.sql